---
title: "control-funnelplot"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{control-funnelplot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(funnelplot)
library(ggplot2)
data("example_data", package = "funnelplot")
head(example_data)
```

### The control argument

The control argument to `funnel` is used...

### pointTarget

```{r}
# outcome ~ covariates | cluster ID
f1 <- funnel(test ~ gender  +age| hosp_id, pointTarget(), data = example_data)
plot(f1)
```

```{r}
# outcome ~ covariates | cluster ID
f1s <- funnel(test ~ gender +age | hosp_id, pointTarget(standardised = TRUE), 
  data = example_data)
plot(f1s)
```

### distTarget

```{r}
# outcome ~ covariates | cluster ID
f2 <- funnel(test ~ gender + age | hosp_id, distTarget(limits = c(0.01,0.05),
  standardised = FALSE), data = example_data)
plot(f2)
```

```{r}
# outcome ~ covariates | cluster ID
f2s <- funnel(test ~ gender + age | hosp_id, distTarget(limits = c(0.01,0.05),
  standardised = TRUE), data = example_data)
plot(f2s)
```

